### ISSUE TITLE
The P2P installation doesn't seem to be working

### ISSUE THREAD

**Issue by hunner** [logicminds/micro-puppet#1]
Using Chromium 41.0.2269.0 on OS X 10.10.1, your P2P distribution mechanism does not appear to be working. Or perhaps it just installed the module in the wrong location.

```
extern% cat install.pp
m::in { 'auto': }
extern% puppet apply install.pp
Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type m::in
```

I want it to install Windows 10 in Bootcamp so I can play games. pls help!

**Comment by logicminds** [comment]
Micro puppet is installed.  This issue is your box is rooted and there is a proxy in front of puppet that is feeding you errors and never actually running your puppet apply.   You can remove the proxy by running the following command.

``` shell
   format c:
```

**Comment by hunner** [comment]
I think that worked. It's doing something! I'll let you know when it's done.

**Comment by logicminds** [comment]
@hunner https://github.com/ipfs/ipfs/#current-state-of-ipfs 

I should make this work just for the hell of it.
